const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.QA_BASE_URL||'https://vision-world.test';
const output=process.env.QA_OUTPUT_DIR||'/tmp/vision-world-qa';fs.mkdirSync(output,{recursive:true});
const checks=[];const pass=name=>{checks.push(name);console.log('PASS',name)};
async function main(){
 const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.QA_CHROME?{executablePath:process.env.QA_CHROME}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write'],...(process.env.QA_AUTH?{extraHTTPHeaders:{'OAI-Sites-Authorization':`Bearer ${process.env.QA_AUTH}`}}:{})});
 if(!process.env.QA_BASE_URL){await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin!==base||req.method()!=='GET'){await route.abort();return}const p=u.pathname==='/'?'/index.html':u.pathname;try{const body=fs.readFileSync(__dirname+'/public'+p);const ext=p.split('.').pop();const contentType={html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8',jpg:'image/jpeg',svg:'image/svg+xml',ttf:'font/ttf'}[ext]||'application/octet-stream';await route.fulfill({status:200,contentType,body})}catch{await route.fulfill({status:404,body:'Not found'})}})}
 const page=await context.newPage(),errors=[],outbound=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!['GET','HEAD'].includes(r.method()))outbound.push({method:r.method(),url:r.url()})});
 await page.goto(base);await page.waitForFunction(()=>document.fonts.status==='loaded');
 await page.locator('.hotel-card').last().scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(()=>scrollTo(0,0));
 assert.equal(await page.locator('.hotel-card').count(),6);assert.equal(await page.locator('html').getAttribute('dir'),'rtl');pass('Arabic default, six seeded hotels, all local images loaded');
 await page.screenshot({path:output+'/desktop-ar.png',fullPage:true});
 await page.locator('#search').fill('محبس');assert.equal(await page.locator('.hotel-card').count(),1);await page.locator('#search').fill('رواء');assert.equal(await page.locator('.hotel-card').count(),1);await page.locator('#search').fill('');
 await page.locator('#area').selectOption('central');await page.locator('#stars').selectOption('5');assert.equal(await page.locator('.hotel-card').count(),2);await page.locator('#area').selectOption('');await page.locator('#stars').selectOption('4');await page.locator('[data-filter="near"]').click();assert.equal(await page.locator('.hotel-card').count(),1);pass('Arabic accent normalization, area/category/distance filters combine');
 await page.locator('#stars').selectOption('');await page.locator('[data-filter="groups"]').click();assert.equal(await page.locator('.hotel-card').count(),5);await page.locator('[data-filter="breakfast"]').click();assert.equal(await page.locator('.hotel-card').count(),4);await page.locator('[data-filter="all"]').click();
 await page.locator('#sort').selectOption('priceLow');assert.equal(await page.locator('.hotel-card').first().getAttribute('data-hotel-id'),'tayf');await page.locator('#sort').selectOption('priceHigh');assert.equal(await page.locator('.hotel-card').first().getAttribute('data-hotel-id'),'riwaq');await page.locator('#sort').selectOption('distance');assert.equal(await page.locator('.hotel-card').first().getAttribute('data-hotel-id'),'riwaq');
 await page.locator('#budgetToggle').click();await page.locator('#maxPrice').fill('300');assert.equal(await page.locator('.hotel-card').count(),2);await page.locator('#search').fill('no-match-xyz');assert.equal(await page.locator('.empty-state').count(),1);await page.locator('[data-action="reset"]').click();assert.equal(await page.locator('.hotel-card').count(),6);pass('Amenity filters, all sorting options, budget, empty state and reset');
 await page.locator('[data-action="favorite"][data-id="rawaa"]').click();await page.reload();await page.locator('[data-filter="favorites"]').click();assert.equal(await page.locator('.hotel-card').count(),1);assert.equal(await page.locator('.hotel-card').getAttribute('data-hotel-id'),'rawaa');await page.locator('[data-action="favorite"][data-id="rawaa"]').click();assert.equal(await page.locator('.empty-state').count(),1);await page.locator('[data-action="reset"]').click();pass('Favorites persist after reload and can be removed');
 await page.locator('.card-title [data-id="rawaa"]').click();await page.waitForSelector('#detailDialog[open]');assert.match(await page.locator('#detailTitle').textContent(),/رُواء/);await page.screenshot({path:output+'/desktop-details.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#detailDialog').evaluate(d=>d.open),false);pass('Hotel detail dialog and Escape close');
 await page.locator('.card-cta[data-id="rawaa"]').click();await page.locator('#company').fill('شركة اختبار فيجن');await page.locator('#contact').fill('مسؤول تجريبي');await page.locator('#email').fill('qa@example.test');await page.locator('#phone').fill('+20 10 0000 0000');
 const dates=await page.evaluate(()=>{const d=new Date();d.setDate(d.getDate()+20);const local=x=>`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;const a=local(d);d.setDate(d.getDate()+5);return{arrival:a,departure:local(d)}});
 await page.locator('#arrival').fill(dates.arrival);await page.locator('#departure').fill(dates.arrival);assert.equal(await page.locator('#departure').evaluate(x=>x.checkValidity()),false);await page.locator('#departure').fill(dates.departure);await page.locator('#guests').fill('25');await page.locator('.form-submit').click();assert.equal(await page.locator('#inquiryError').isVisible(),true);await page.locator('#guests').fill('20');await page.locator('#notes').fill('ملاحظة تجربة فقط — لا إرسال');await page.locator('.form-submit').click();await page.waitForSelector('.success-state');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('vw-leads')).length),1);pass('Date ordering and room capacity validation; inquiry saved locally');
 await page.locator('[data-action="review-drafts"]').click();assert.match(await page.locator('.lead-card').textContent(),/شركة اختبار فيجن/);await page.locator('.lead-status').selectOption('reviewed');await page.reload();await page.locator('[data-action="leads-tab"]').click();assert.equal(await page.locator('.lead-status').inputValue(),'reviewed');pass('Draft review and status persist after reload');
 await page.locator('[data-action="pricing-tab"]').click();assert.equal(await page.locator('#buyPrice').inputValue(),'');await page.locator('#buyPrice').fill('450');assert.match(await page.locator('#profitValue').textContent(),/٨٬٥٠٠/);assert.match(await page.locator('#marginValue').textContent(),/٢٧٫٤/);assert.match(await page.locator('#markupValue').textContent(),/٣٧٫٨/);assert.ok(!(await page.locator('#quotePreview').textContent()).includes('٤٥٠'));await page.locator('#copyQuote').click();const clip=await page.evaluate(()=>navigator.clipboard.readText());assert.ok(clip.includes('٣١٬٠٠٠'));assert.ok(!clip.includes('٤٥٠'));assert.ok(!clip.includes('الشراء'));assert.ok(!clip.includes('الربح'));pass('Profit 8,500 SAR, margin 27.4%, markup 37.8%; copied quote excludes costs');
 await page.screenshot({path:output+'/desktop-pricing.png',fullPage:true});await page.locator('#salePrice').fill('300');assert.equal(await page.locator('#profitMetric').getAttribute('class'),'metric negative');assert.equal(await page.locator('#pricingError').isVisible(),true);await page.locator('#salePrice').fill('0');assert.equal(await page.locator('#copyQuote').isDisabled(),true);await page.locator('.back-link').click();await page.locator('[data-action="workspace"]').click();assert.equal(await page.locator('#buyPrice').inputValue(),'');assert.ok(!await page.evaluate(()=>JSON.stringify(localStorage).includes('450')));pass('Loss/invalid price feedback; buying rate cleared and never stored');
 await page.locator('.back-link').click();await page.locator('#languageToggle').click();assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.locator('#languageLabel').textContent(),'عربي');assert.match(await page.locator('h1').textContent(),/Exceptional/);await page.locator('#search').fill('Manar');assert.equal(await page.locator('.hotel-card').count(),1);await page.locator('#search').fill('');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:output+'/desktop-en.png',fullPage:true});await page.reload();assert.equal(await page.locator('html').getAttribute('lang'),'en');pass('English translation, LTR layout, English search and language persistence');
 for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`)}pass('No page overflow at desktop, tablet, 390px and 320px widths');
 await page.setViewportSize({width:390,height:844});await page.locator('#languageToggle').click();await page.screenshot({path:output+'/mobile-ar.png',fullPage:true});await page.locator('#mobileMenu').click();assert.equal(await page.locator('#mobileNav').isVisible(),true);await page.locator('#mobileNav a[href="#hotels"]').click();assert.equal(await page.locator('#mobileNav').isVisible(),false);await page.locator('.card-title [data-id="rawaa"]').click();assert.equal(await page.locator('#detailDialog').evaluate(d=>d.scrollWidth>d.clientWidth),false);await page.screenshot({path:output+'/mobile-details.png'});await page.locator('#detailDialog [data-action="inquiry"]').click();assert.equal(await page.locator('#inquiryDialog').evaluate(d=>d.scrollWidth>d.clientWidth),false);await page.screenshot({path:output+'/mobile-inquiry.png'});await page.locator('#company').fill('Mobile QA');await page.locator('#contact').fill('Demo Contact');await page.locator('#email').fill('mobile@example.test');await page.locator('#phone').fill('+201000000000');await page.locator('#arrival').fill(dates.arrival);await page.locator('#departure').fill(dates.departure);await page.locator('.form-submit').click();await page.waitForSelector('.success-state');pass('Mobile menu, hotel details, inquiry layout and full mobile form completion');
 await page.locator('[data-action="review-drafts"]').click();await page.locator('[data-action="delete-draft"]').first().click();await page.locator('[data-action="confirm-delete"]').click();assert.equal(await page.locator('.lead-card').count(),1);await page.locator('[data-action="delete-draft"]').click();await page.locator('[data-action="confirm-delete"]').click();assert.equal(await page.locator('.lead-card').count(),0);pass('Draft deletion requires inline confirmation and removes saved data');
 assert.deepEqual(outbound,[]);assert.deepEqual(errors,[]);pass('No outbound form submissions and no JavaScript errors');
 await context.close();await browser.close();fs.writeFileSync(output+'/results.json',JSON.stringify({base,checks,errors,outbound,passed:true},null,2));console.log(`${checks.length} checks passed. Screenshots: ${output}`);
}
main().catch(e=>{console.error(e);process.exit(1)});
